//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtbCalculator.CalculationServiceClients.Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reference.ICalculationService")]
    public interface ICalculationWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/Calculate", ReplyAction="http://tempuri.org/ICalculationService/CalculateResponse")]
        VtbCalculator.BusinessLogic.Models.CalculationResultModel Calculate(VtbCalculator.BusinessLogic.Models.CalculationRequestModel calculationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/Calculate", ReplyAction="http://tempuri.org/ICalculationService/CalculateResponse")]
        System.Threading.Tasks.Task<VtbCalculator.BusinessLogic.Models.CalculationResultModel> CalculateAsync(VtbCalculator.BusinessLogic.Models.CalculationRequestModel calculationRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculationServiceChannel : VtbCalculator.CalculationServiceClients.Reference.ICalculationWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationWcfServiceClient : System.ServiceModel.ClientBase<VtbCalculator.CalculationServiceClients.Reference.ICalculationWcfService>, VtbCalculator.CalculationServiceClients.Reference.ICalculationWcfService {
        
        public CalculationWcfServiceClient() {
        }
        
        public CalculationWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VtbCalculator.BusinessLogic.Models.CalculationResultModel Calculate(VtbCalculator.BusinessLogic.Models.CalculationRequestModel calculationRequest) {
            return base.Channel.Calculate(calculationRequest);
        }
        
        public System.Threading.Tasks.Task<VtbCalculator.BusinessLogic.Models.CalculationResultModel> CalculateAsync(VtbCalculator.BusinessLogic.Models.CalculationRequestModel calculationRequest) {
            return base.Channel.CalculateAsync(calculationRequest);
        }
    }
}
