//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtbCalculator.ServiceClients.Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reference.ICalculationService")]
    public interface ICalculationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/Sum", ReplyAction="http://tempuri.org/ICalculationService/SumResponse")]
        decimal Sum(decimal value1, decimal value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/Sum", ReplyAction="http://tempuri.org/ICalculationService/SumResponse")]
        System.Threading.Tasks.Task<decimal> SumAsync(decimal value1, decimal value2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculationServiceChannel : VtbCalculator.ServiceClients.Reference.ICalculationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationServiceClient : System.ServiceModel.ClientBase<VtbCalculator.ServiceClients.Reference.ICalculationService>, VtbCalculator.ServiceClients.Reference.ICalculationService {
        
        public CalculationServiceClient() {
        }
        
        public CalculationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Sum(decimal value1, decimal value2) {
            return base.Channel.Sum(value1, value2);
        }
        
        public System.Threading.Tasks.Task<decimal> SumAsync(decimal value1, decimal value2) {
            return base.Channel.SumAsync(value1, value2);
        }
    }
}
